# Generated by Django 6.0.7 on 2026-08-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_owner_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='formversion',
            name='conditional_rules_snapshot',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'equals'), ('not_equals', 'not_equals'), ('contains', 'contains'), ('greater_than', 'greater_than'), ('is_empty', 'is_empty')], max_length=20)),
                ('comparison_value', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('show', 'show'), ('hide', 'hide'), ('require', 'require')], max_length=20)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='forms.form')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='forms.field')),
                ('trigger_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='forms.field')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('form_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='forms.formversion')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.submission')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=1024)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forms.submission')),
            ],
        ),
    ]
